-- Your SQL goes here
CREATE TABLE posts ( 
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	author_id INTEGER NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	title TEXT NOT NULL, 
	body TEXT NOT NULL, 
	FOREIGN KEY (author_id) REFERENCES users (id) 
);